# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 22 Sep 2014 15:19:56 +0000
*               @ALL          0
*               @user         8
