froxly_base_check_free_proxy = 'froxly_base_check_free_proxy'
froxly_url_free_proxy_prefix = 'froxly_free_proxy_'
froxly_url_free_proxy_to_check_prefix = 'froxly_free_proxy_to_check_'
froxly_url_free_proxy_finish_prefix = 'froxly_free_proxy_finish_'
froxly_url_free_proxy_log_prefix = 'froxly_free_proxy_log_'
froxly_rnd_free_proxy_log = 'froxly_rnd_free_proxy_log'

ugently_user_agent_value = 'ugently_user_agent_value'